services:
  prometheus:
    image: prom/prometheus:v3.5.0
    ports:
      - "127.0.0.1:19090:9090"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml:ro
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.retention.time=1h
